List searchCategories = [
  "Lojas",
  "Seleções do editor",
  "Coleções",
  "Guias",
  "Vídeos",
];

List searchImages = [
  "assets/images/pesquisa_1.jpg",
   "assets/images/pesquisa_2.jpg",
   "assets/images/pesquisa_3.jpg",
   "assets/images/pesquisa_4.jpg",
   "assets/images/pesquisa_5.jpg",
   "assets/images/pesquisa_6.jpg",
   "assets/images/pesquisa_7.jpg",
   "assets/images/pesquisa_8.jpg",
   "assets/images/pesquisa_9.jpg",
   "assets/images/pesquisa_10.jpg",
   "assets/images/publicacao_2.jpg",
   "assets/images/publicacao_3.jpg",
   "assets/images/publicacao_1.jpg",
   "assets/images/publicacao_4.jpg",
   "assets/images/perfil_4.jpg",
   "assets/images/pesquisa_1.jpg",
   "assets/images/pesquisa_2.jpg",
   "assets/images/pesquisa_3.jpg",
   "assets/images/pesquisa_4.jpg",
   "assets/images/pesquisa_5.jpg",
   "assets/images/pesquisa_6.jpg",
];

List profileImages = [
  "assets/images/publicacao_1.jpg",
   "assets/images/pesquisa_3.jpg",
   "assets/images/perfil_3.jpg",
   "assets/images/pesquisa_5.jpg",
   "assets/images/pesquisa_10.jpg",
   "assets/images/publicacao_3.jpg",
   "assets/images/pesquisa_1.jpg",
   "assets/images/publicacao_1.jpg",
   "assets/images/pesquisa_3.jpg",
   "assets/images/publicacao_3.jpg",
   "assets/images/pesquisa_1.jpg",
   "assets/images/pesquisa_5.jpg",
   "assets/images/publicacao_1.jpg",
   "assets/images/pesquisa_3.jpg",
   "assets/images/pesquisa_1.jpg",
];